#! /usr/bin/env python2.7
from __future__ import absolute_import, print_function
from logging import basicConfig, getLogger, DEBUG
from os.path import abspath
from sys import path as sys_path

root = abspath(".")

if "." not in sys_path and root not in sys_path:
    sys_path[:0] = [root]

basicConfig(level=DEBUG)

import cherrypy
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from dozer.dbpool import ConnectionPool, SQLitePool
from dozer.app import DreadfulBulldozer

cherrypy.config.update({
        'server.socket_host': '127.0.0.1',
        'server.socket_port': 8080,
        'log.screen': False,
    })

config = {
    '/': {
        'tools.trailing_slash.on': True,
        'tools.staticdir.root': root,
    },
    '/static': {
        'tools.staticdir.on': True,
        'tools.staticdir.dir': 'static',
    },
    '/bootstrap': {
        'tools.staticdir.on': True,
        'tools.staticdir.dir': 'bootstrap',
    },
    '/jquery': {
        'tools.staticdir.on': True,
        'tools.staticdir.dir': 'jquery',
    },
}

engine = create_engine("sqlite:///" + root + "/dozer.db")
app = cherrypy.tree.mount(
    DreadfulBulldozer(server_root=root,
                      session_class=sessionmaker(bind=engine)),
    "/", config)
cherrypy.engine.start()
cherrypy.engine.block()
exit(0)

##  Local variables:
##  mode: Python
##  tab-width: 8
##  indent-tabs-mode: nil
##  End:
##  vi: set expandtab tabstop=8
